### ISSUE TITLE
bug Digital Smarters

### ISSUE THREAD

**Issue by DigitalSmarters** [Samsung/Tizen.Issues#4]
PLEASE READ THE FOLLOWING GUIDELINES FIRST:

This form is only for reporting bugs found in the Tizen platform including SDK & IDE & Tools and while developing Tizen applications. We may remove any report that does not meet the purpose(Platform bug tracking) without notice in accordance with our "Terms of Service".

-------------------------------------------------------------------------------------------

**Describe the platform bug**
A clear and concise description of what the issue is.

**To Reproduce(For bugs that require reproduction)**
3. See error

**Expected behavior(For bugs that require reproduction)**

**Screenshots(For bugs that require reproduction or Current issue status)**

**TV(please complete the following information):**
 - Device: [e.g. SmartTV or SmartMonitor Etc.]
 - Purchase date information: [e.g. 2024.04]
 - OS version: [e.g. Tizen8.0 or Tizen9.0]
 - SDK version: [e.g Tizen SDK 5.0 or Tizen SDK 6.0]

**Appliances(please complete the following information):**
 - Device: [e.g. Family Hub Refrigerator]
 - Purchase date information: [e.g. 2024.04]
 - OS version: [e.g. Tizen8.0 or Tizen9.0]
 - SDK version: [e.g Tizen SDK 5.0 or Tizen SDK 6.0]

**Smartphone (please complete the following information):**
 - Device: [e.g. SamsungZ3 or SamsungZ4]
 - Purchase date information: [e.g. 2024.04]
 - OS version: [e.g. Tizen8.0 or Tizen9.0]
 - SDK version: [e.g Tizen SDK 5.0 or Tizen SDK 6.0]

**Smartwatch (please complete the following information):**
 - Device: [e.g. Samsung Galaxy Watch Active or Samsung Galaxy Watch 3]
 - Purchase date information: [e.g. 2024.04]
 - OS version: [e.g. Tizen8.0 or Tizen9.0]
 - SDK version: [e.g Tizen SDK 5.0 or Tizen SDK 6.0]

**Additional context**

-------------------------------------------------------------------------------------------

Disclaimer:

Please note, by submitting this bug report, you acknowledge that Tizen may use information included in the bug report to diagnose technical issues including bugs and to improve our platform and services, in accordance with our Privacy Policy(Privacy Policy | Tizen), Linux Foundation Privacy Policy in the existing Tizen Privacy Policy(https://www.linuxfoundation.org/legal/privacy-policy), and you agree that we may share it with engineering partners potentially impacted by your bug.

**Comment by winstone77** [comment]
close due to no bug information
